name: R88 MEDIA
favicon: null
layout_spectrum: 0.42408950231038034
typography_spectrum: 0.5464043056126684
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.7443318290170282
  lightness: 0.30717852688394487
  saturation: 0.5643034419044852
  rhythmicContrast: 0.42320069624111056
purpose: []
