name: R88 MEDIA
favicon: null
layout_spectrum: 0.42408950231038034
typography_spectrum: 0.5464043056126684
title: R88 TEST SITE
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#1b80bd'
    - '#e8af9d'
    - '#8c3e36'
    - '#1c0710'
  brandStrength: 0.875
  lightness: 0.875
  saturation: 0.8125
  rhythmicContrast: 0
purpose: []
